server {
    listen 80;
    server_name localhost;

    location /api {
        proxy_pass http://bazan-dify-api:5001;
        include /etc/nginx/proxy_params;
    }

    location /v1 {
        proxy_pass http://bazan-dify-api:5001;
        include /etc/nginx/proxy_params;
    }

    location /console/api {
        proxy_pass http://bazan-dify-api:5001;
        include /etc/nginx/proxy_params;
    }

    location / {
        proxy_pass http://bazan-dify-web:3000;
        include /etc/nginx/proxy_params;
    }
}
